---
on:
  workflow_call:
    inputs:
      uv_lint_group_name:
        type: string
        default: ""
        description: Optional uv dependency group name.
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup UV
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        if: ${{ inputs.uv_lint_group_name != '' }}
        run: uv sync --group ${{ inputs.uv_lint_group_name }}
      - name: Lint YAML files (with dependencies)
        if: ${{ inputs.uv_lint_group_name != '' }}
        run: uv run yamllint .

      - name: Lint YAML files (standalone)
        if: ${{ inputs.uv_lint_group_name == '' }}
        run: uv tool run yamllint .
