---
on:
  workflow_call:
    inputs:
      include_terraform:
        description: 'Whether to include terraform pre-commit checks'
        default: false
        required: false
        type: boolean

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Terraform
        if: ${{ inputs.include_terraform }}
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Setup TFLint
        if: ${{ inputs.include_terraform }}
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install the project
        run: uv sync --all-extras --all-groups

      - name: Install Checkov
        if: ${{ inputs.include_terraform }}
        run: pipx install checkov

      - name: Run Prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
