---
name: Security checks

on:
  workflow_call:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@30d5bb91af1a771378349dbbb0c82129392acf70 # v3.95.6
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown

  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@67a458d90fa11fb1463e91e7f4c8f068b5863c7f # v1.0.1

  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Scan for secrets
        run: detect-secrets scan --all-files > .secrets.baseline --exclude-files '.git*'
