---
on:
  workflow_call:
    inputs:
      uv_sync_groups:
        type: string
        default: --all-extras --all-groups
      pytest_target:
        type: string
        default: ""
jobs:
  python-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup UV
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync ${{  inputs.uv_sync_groups  }}
      - name: Ensure pytest-cov is available
        run: uv pip install pytest-cov
      - name: Run tests
        run: uv run pytest ${{  inputs.pytest_target  }} -v --cov=src
          --cov-report=term-missing
